# $HOME/.config/alacritty/alacritty.toml

[window]
padding.x = 10
padding.y = 0

[font]
normal.family = "BerkeleyMono Nerd Font"
bold.family = "BerkeleyMono Nerd Font"
italic.family = "BerkeleyMono Nerd Font"
bold_italic.family = "BerkeleyMono Nerd Font"

size = 10.0

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[shell]
program = "/usr/bin/fish"
